version: "3.8"

services:
  database:
    image: postgres:15.0-alpine
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - .postgres_data:/var/lib/postgresql/data

  broker:
    image: redis:alpine
    container_name: redis
    restart: always

  celery:
    build:
      dockerfile: Dockerfile
    container_name: celery
    restart: always
    env_file:
      - .env
    command: bash -c "celery -A ke_service worker --beat --scheduler django --loglevel=info" #playwright install --with-deps chromium &&
    depends_on:
      - myapp

  celery_flower:
    image: mher/flower
    container_name: celery_flower
    restart: always
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - celery

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx/certbot/conf:/etc/letsencrypt:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
    links:
      - myapp
    depends_on:
      - myapp

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt:rw
      - ./nginx/certbot/www:/var/www/certbot:rw
#    command: certonly --webroot --webroot-path=/var/www/certbot/ --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN} -d ${CERTBOT_WWW_DOMAIN}
    depends_on:
      - nginx

  myapp:
    build: .
    container_name: myapp
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    command: /app/entrypoint.sh
    depends_on:
      - database
      - broker

volumes:
  postgres_data:
